apiVersion: apps/v1
kind: Deployment
metadata:
  name: enclave-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enclave
  template:
    metadata:
      labels:
        app: enclave
    spec:
      containers:
      - name: enclave-aba86e99-db6c-40cd-a1b1-482f92422afa
        image: public.ecr.aws/s0k4s5w7/enclave-wallet:latest
        # command: ["/home/run.sh"]
        imagePullPolicy: Always
        resources:
          limits:
            # aws.ec2.nitro/nitro_enclaves: "1"
            hugepages-2Mi: 100Mi
            cpu: 250m
          requests:
            # aws.ec2.nitro/nitro_enclaves: "1"
            hugepages-2Mi: 100Mi
        volumeMounts:
        - mountPath: /hugepages-2Mi
          name: hugepage-2mi
          readOnly: false
        # Enable if 1Gi pages are required
        #- mountPath: /hugepages-1Gi
        #  name: hugepage-1gi
        #  readOnly: false
      volumes:
      - name: hugepage-2mi
        emptyDir:
          medium: HugePages-2Mi
      - name: hugepage-1gi
        emptyDir:
          medium: HugePages-1Gi
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
