package com.github.mrgatto.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.math.BigDecimal;

@DynamoDBTable(tableName="UserAccount")
public class UserAccount {
    private String userid;
    private String id;
    private String email;
    private String btcAddress;
    private String btcEncryptedPrivateAddressWIF;

    public void setUserId(String userId) {
        this.userid = userId;
    }

    @DynamoDBAttribute(attributeName="id")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName="btcAddress")
    public String getBtcAddress() {
        return btcAddress;
    }

    public void setBtcAddress(String btcAddress) {
        this.btcAddress = btcAddress;
    }

    @DynamoDBAttribute(attributeName="btcEncryptedPrivateAddressWIF")
    public String getBtcEncryptedPrivateAddressWIF() {
        return btcEncryptedPrivateAddressWIF;
    }

    public void setBtcEncryptedPrivateAddressWIF(String btcEncryptedPrivateAddressWIF) {
        this.btcEncryptedPrivateAddressWIF = btcEncryptedPrivateAddressWIF;
    }

    //@DynamoDBAttribute(attributeName="email")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "email-index", attributeName = "email")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @DynamoDBHashKey(attributeName = "userid")
    @DynamoDBAutoGeneratedKey
    public String getUserId() { return userid; }

}

